name: OWASP ZAP Scan

on:
  push:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "https://demo.testfire.net"
          cmd_options: "-a"
